spring:
  liquibase:
    contexts: local
  datasource:
    url: jdbc:h2:~/client-demo
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  logging:
    level:
      "liquibase": info


server:
  port: 8080


kycService:
  url: http://localhost:8081/kyc
